In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import xlrd

In [2]:
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.5
NumPy version: 2.5.2

In [3]:
import openpyxl

print(openpyxl.__version__)

3.1.5

In [4]:
file_path=r"C:\Users\Kishore\Downloads\Jupyter_notebook\Daily_Projects\Day_06\Online Retail.xlsx"

In [5]:
df=pd.read_excel(file_path,sheet_name="Online Retail",engine="openpyxl")

In [6]:
df.head(25)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom

In [7]:
df.shape

(541909, 8)

In [8]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [9]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [11]:
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

Rows: 541909
Columns: 8

In [12]:
len(df)

541909

In [13]:
df["InvoiceNo"].nunique()

25900

In [14]:
print(df.columns.to_list())

['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

In [15]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print(df.columns.tolist())

print(df.info())

print(df.head(10))

print(df.tail(10))

Rows: 541909
Columns: 8
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']
<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB
None
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
5    536365     22752         SET 7 BABUSHKA NESTING BOXES         2
6    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6
7    536366     22633               HAND WARMER UNION JACK         6
8    536366     22632            HAND WARMER RED POLKA DOT         6
9    536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32

          InvoiceDate  UnitPrice  CustomerID         Country
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
5 2010-12-01 08:26:00       7.65     17850.0  United Kingdom
6 2010-12-01 08:26:00       4.25     17850.0  United Kingdom
7 2010-12-01 08:28:00       1.85     17850.0  United Kingdom
8 2010-12-01 08:28:00       1.85     17850.0  United Kingdom
9 2010-12-01 08:34:00       1.69     13047.0  United Kingdom
       InvoiceNo StockCode                      Description  Quantity  \
541899    581587     22726       ALARM CLOCK BAKELIKE GREEN         4
541900    581587     22730       ALARM CLOCK BAKELIKE IVORY         4
541901    581587     22367  CHILDRENS APRON SPACEBOY DESIGN         8
541902    581587     22629              SPACEBOY LUNCH BOX         12
541903    581587     23256      CHILDRENS CUTLERY SPACEBOY          4
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899     CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138    BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice  CustomerID Country
541899 2011-12-09 12:50:00       3.75     12680.0  France
541900 2011-12-09 12:50:00       3.75     12680.0  France
541901 2011-12-09 12:50:00       1.95     12680.0  France
541902 2011-12-09 12:50:00       1.95     12680.0  France
541903 2011-12-09 12:50:00       4.15     12680.0  France
541904 2011-12-09 12:50:00       0.85     12680.0  France
541905 2011-12-09 12:50:00       2.10     12680.0  France
541906 2011-12-09 12:50:00       4.15     12680.0  France
541907 2011-12-09 12:50:00       4.15     12680.0  France
541908 2011-12-09 12:50:00       4.95     12680.0  France

In [16]:
missing_count=df.isna().sum()
missing_count

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [17]:
missing_percentage=(df.isna().sum()/len(df))*100
missing_percentage

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

In [18]:
missing_summary=pd.DataFrame(
    {"Missing Count":df.isna().sum(),
     "Missing Percentage:":df.isna().sum()/len(df)*100}
)
missing_summary.sort_values("Missing Count")

             Missing Count  Missing Percentage:
InvoiceNo                0             0.000000
StockCode                0             0.000000
Quantity                 0             0.000000
InvoiceDate              0             0.000000
Country                  0             0.000000
UnitPrice                0             0.000000
Description           1454             0.268311
CustomerID          135080            24.926694

In [19]:
missing_description=df[df["Description"].isna()]
print("no of null description:",len(missing_description))
missing_description.head(10)

no of null description: 1454

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

In [20]:
missing_customer = df[df["CustomerID"].isna()]

print("Rows with missing CustomerID:", len(missing_customer))

missing_customer.head(10)

Rows with missing CustomerID: 135080

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,2010-12-01 14:32:00,0.43,NaN,United Kingdom

In [21]:
missing_customer["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
False    134697
True        383
Name: count, dtype: int64

In [22]:
missing_customer["InvoiceNo"]=missing_customer["InvoiceNo"].astype(str).copy()

In [23]:
missing_customer_summary=missing_customer[["Quantity","UnitPrice"]].describe()
missing_customer_summary

            Quantity      UnitPrice
count  135080.000000  135080.000000
mean        1.995573       8.076577
std        66.696153     151.900816
min     -9600.000000  -11062.060000
25%         1.000000       1.630000
50%         1.000000       3.290000
75%         3.000000       5.450000
max      5568.000000   17836.460000

In [24]:
df["LineValue"] = df["Quantity"] * df["UnitPrice"]
missing_customer["LineValue"]=missing_customer["Quantity"]*missing_customer["UnitPrice"]

In [25]:
print("Total value of transaction without Customer ID:",missing_customer["LineValue"].sum())
print("Total value of transaction overall: ",df["LineValue"].sum())

Total value of transaction without Customer ID: 1447682.12
Total value of transaction overall:  9747747.934

In [26]:
missing_customer_LineValue_pct=(missing_customer["LineValue"].sum()/df["LineValue"].sum()*100)
print(f"missing_customer_LineValue_pct:{missing_customer_LineValue_pct:,.2f}")

missing_customer_LineValue_pct:14.85

In [27]:
missing_customer = df[df["CustomerID"].isna()].copy()

In [28]:
missing_customer["LineValue"] = (
    missing_customer["Quantity"] *
    missing_customer["UnitPrice"]
)

In [29]:
df_raw=df.copy()

In [30]:
missing_customer["LineValue"] = (
    missing_customer["Quantity"] *
    missing_customer["UnitPrice"]
)

print("Missing CustomerID value:",
      missing_customer["LineValue"].sum())

print("Overall value:",
      df["LineValue"].sum())

print(
    "Percentage of value:",
    round(
        missing_customer["LineValue"].sum()
        / df["LineValue"].sum()
        * 100,
        2
    )
)

Missing CustomerID value: 1447682.12
Overall value: 9747747.934
Percentage of value: 14.85

In [31]:
missing_description = df[df["Description"].isna()].copy()

print("Missing Description:", len(missing_description))

print(
    "Missing Description + zero price:",
    (missing_description["UnitPrice"] == 0).sum()
)

print(
    "Missing Description + non-zero price:",
    (missing_description["UnitPrice"] != 0).sum()
)

missing_description[["Quantity", "UnitPrice"]].describe()

Missing Description: 1454
Missing Description + zero price: 1454
Missing Description + non-zero price: 0

          Quantity  UnitPrice
count  1454.000000     1454.0
mean     -9.359697        0.0
std     243.238758        0.0
min   -3667.000000        0.0
25%     -24.000000        0.0
50%      -3.000000        0.0
75%       4.000000        0.0
max    5568.000000        0.0

In [32]:
print("Negative Quantity:",(df["Quantity"]<0).sum())
print("Zero Quantity:",(df["Quantity"]==0).sum())
print("Positive Quantity:",(df["Quantity"]>0).sum())
print("-------------------------------------------")
print("Negative UnitPrice:",(df["UnitPrice"]<0).sum())
print("Zero UnitPrice:",(df["UnitPrice"]==0).sum())
print("Positive UnitPrice:",(df["UnitPrice"]>0).sum())

Negative Quantity: 10624
Zero Quantity: 0
Positive Quantity: 531285
-------------------------------------------
Negative UnitPrice: 2
Zero UnitPrice: 2515
Positive UnitPrice: 539392

In [33]:
negative_quantity = df[df["Quantity"] < 0]

print("Negative quantity rows:", len(negative_quantity))

negative_quantity[[
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID",
    "Country"
]].head(20)

Negative quantity rows: 10624

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany

In [34]:
print(
    "Negative Quantity & Cancellation Invoice:",
    negative_quantity["InvoiceNo"].astype(str).str.startswith("C").sum()
)

Negative Quantity & Cancellation Invoice: 9288

In [35]:
print(
    "Negative Quantity + Normal Invoice:",
    (~negative_quantity["InvoiceNo"].astype(str).str.startswith("C")).sum()
)

Negative Quantity + Normal Invoice: 1336

In [36]:
print(
    "Negative Quantity + Cancellation Invoice:",
    negative_quantity["InvoiceNo"].astype(str).str.startswith("C").sum()
)

print(
    "Negative Quantity + Normal Invoice:",
    (~negative_quantity["InvoiceNo"].astype(str).str.startswith("C")).sum()
)

Negative Quantity + Cancellation Invoice: 9288
Negative Quantity + Normal Invoice: 1336

In [37]:
normal_negative = negative_quantity[
    ~negative_quantity["InvoiceNo"].astype(str).str.startswith("C")
].copy()

print("Rows:", len(normal_negative))

normal_negative[[
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID",
    "Country"
]].head(30)

Rows: 1336

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7208,537016,21836,NaN,-15,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7209,537017,47556B,NaN,-69,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7210,537018,84562A,NaN,-3,2010-12-03 15:42:00,0.0,NaN,United Kingdom
7211,537019,37474,NaN,-15,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7212,537020,21807,NaN,-30,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7213,537021,21011,NaN,-20,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7291,537027,18098C,NaN,-140,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7292,537028,21696,NaN,-320,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7293,537029,37476,NaN,-6,2010-12-03 16:37:00,0.0,NaN,United Kingdom
7313,537032,21275,?,-30,2010-12-03 16:50:00,0.0,NaN,United Kingdom

In [38]:
print("Negative quantity with missing Description:",
      normal_negative["Description"].isna().sum())

print("Negative quantity with zero UnitPrice:",
      (normal_negative["UnitPrice"] == 0).sum())

print("Negative quantity with missing CustomerID:",
      normal_negative["CustomerID"].isna().sum())

Negative quantity with missing Description: 862
Negative quantity with zero UnitPrice: 1336
Negative quantity with missing CustomerID: 1336

In [39]:
zero_price = df[df["UnitPrice"] == 0].copy()

print("Zero-price rows:", len(zero_price))

zero_price[[
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID",
    "Country"
]].head(30)

Zero-price rows: 2515

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7194,537002,21651,NaN,70,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom

In [40]:
print("Zero-price + missing Description:",
      zero_price["Description"].isna().sum())

print("Zero-price + negative Quantity:",
      (zero_price["Quantity"] < 0).sum())

print("Zero-price + positive Quantity:",
      (zero_price["Quantity"] > 0).sum())

print("Zero-price + missing CustomerID:",
      zero_price["CustomerID"].isna().sum())

Zero-price + missing Description: 1454
Zero-price + negative Quantity: 1336
Zero-price + positive Quantity: 1179
Zero-price + missing CustomerID: 2475

In [41]:
negative_price = df[df["UnitPrice"] < 0]

negative_price[[
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID",
    "Country"
]]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [42]:
duplicates=df[df.duplicated(keep=False)].copy()
print("No of duplicate rows:",len(duplicates))

No of duplicate rows: 10147

In [43]:
duplicates.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,LineValue
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom,4.95
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom,2.10
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom,1.25
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom,1.25
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom,2.95

In [44]:
duplicates_rows=len(duplicates)
overall=len(df)
duplicates_pct=df.duplicated().sum()/len(df)*100
print("duplicates pct:",round(duplicates_pct,2),"%")

duplicates pct: 0.97 %

In [45]:
duplicates_pct

np.float64(0.9721189350979592)

In [46]:
duplicate = df[df.duplicated(keep=False)].copy()
print("Duplicate rows:",len(duplicate))
print("Duplicate Line Value:",duplicate["LineValue"].sum())
print("Over all Line value:",df["LineValue"].sum())

Duplicate rows: 10147
Duplicate Line Value: 41755.54
Over all Line value: 9747747.934

In [47]:
print("Duplicate Line Value pct:",round(duplicate["LineValue"].sum()/df["LineValue"].sum() *100,2) )

Duplicate Line Value pct: 0.43

In [48]:
duplicate_groups=(df.groupby([
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
]).size()
    .reset_index(name="Count")
    .sort_values("Count",ascending=False)
                 )
duplicate_groups.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Count
146380,555524,22698,PINK REGENCY TEACUP AND SAUCER,1,2011-06-05 11:37:00,2.95,16923.0,United Kingdom,20
146379,555524,22697,GREEN REGENCY TEACUP AND SAUCER,1,2011-06-05 11:37:00,2.95,16923.0,United Kingdom,12
303127,572861,22775,PURPLE DRAWERKNOB ACRYLIC EDWARDIAN,12,2011-10-26 12:46:00,1.25,14102.0,United Kingdom,8
298989,572344,M,Manual,48,2011-10-24 10:43:00,1.50,14607.0,United Kingdom,6
35473,541266,21754,HOME BUILDING BLOCK WORD,1,2011-01-16 16:25:00,5.95,15673.0,United Kingdom,6
35474,541266,21755,LOVE BUILDING BLOCK WORD,1,2011-01-16 16:25:00,5.95,15673.0,United Kingdom,6
16696,538514,21756,BATH BUILDING BLOCK WORD,1,2010-12-12 14:27:00,5.95,15044.0,United Kingdom,6
30356,540524,21756,BATH BUILDING BLOCK WORD,1,2011-01-09 12:53:00,5.95,16735.0,United Kingdom,6
361129,578289,23395,BELLE JARDINIERE CUSHION COVER,1,2011-11-23 14:07:00,3.75,17841.0,United Kingdom,6
107367,550331,85202,HANGING WOOD AND FELT HEART,1,2011-04-17 13:43:00,0.42,15555.0,United Kingdom,5
319059,574481,23084,RABBIT NIGHT LIGHT,1,2011-11-04 12:45:00,2.08,18022.0,United Kingdom,5
7453,537224,70007,HI TEC ALPINE HAND WARMER,1,2010-12-05 16:24:00,1.65,13174.0,United Kingdom,5
86942,547712,22699,ROSES REGENCY TEACUP AND SAUCER,1,2011-03-24 19:31:00,2.95,16905.0,United Kingdom,5
16774,538517,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-12 16:05:00,3.75,17618.0,United Kingdom,5
36390,541414,21755,LOVE BUILDING BLOCK WORD,1,2011-01-17 16:14:00,5.95,18212.0,United Kingdom,4
132354,553657,22131,FOOD CONTAINER SET 3 LOVE HEART,1,2011-05-18 11:28:00,1.95,14583.0,United Kingdom,4
85984,547651,22249,DECORATION WHITE CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom,4
59090,544450,47567B,TEA TIME KITCHEN APRON,1,2011-02-20 12:23:00,5.95,17811.0,United Kingdom,4
59463,544463,22256,FELT FARM ANIMAL CHICKEN,1,2011-02-20 14:31:00,1.25,12988.0,United Kingdom,4
89131,547906,22261,FELT EGG COSY WHITE RABBIT,1,2011-03-28 12:13:00,0.85,14410.0,United Kingdom,4

In [49]:
duplicates_rows_invoice=(
    duplicate_groups.groupby("InvoiceNo") ["Count"].sum().sort_values(ascending=False)
)
duplicates_rows_invoice.head(20)

InvoiceNo
576339    542
579196    533
580727    529
578270    442
573576    435
567656    421
567183    399
575607    377
571441    364
570488    353
572552    352
568346    335
547063    294
569246    285
562031    277
554098    264
570672    259
543040    259
569897    239
572103    223
Name: Count, dtype: int64

In [50]:
top_duplicate_invoices = duplicates_rows_invoice.head(10)

print(top_duplicate_invoices)

InvoiceNo
576339    542
579196    533
580727    529
578270    442
573576    435
567656    421
567183    399
575607    377
571441    364
570488    353
Name: Count, dtype: int64

In [51]:
invoice_576339=df[df["InvoiceNo"].astype(str)=="576339"].copy()
print("invoice_576339 len:",len(invoice_576339))
invoice_576339[
    ["InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
]].head(50)

invoice_576339 len: 542

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
466895,576339,10135,COLOURING PENCILS BROWN TUBE,14,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466896,576339,15044A,PINK PAPER PARASOL,1,2011-11-14 15:27:00,5.79,14096.0,United Kingdom
466897,576339,16238,PARTY TIME PENCIL ERASERS,2,2011-11-14 15:27:00,0.42,14096.0,United Kingdom
466898,576339,16258A,SWIRLY CIRCULAR RUBBERS IN BAG,1,2011-11-14 15:27:00,0.83,14096.0,United Kingdom
466899,576339,17003,BROCADE RING PURSE,2,2011-11-14 15:27:00,0.63,14096.0,United Kingdom
466900,576339,20617,FIRST CLASS PASSPORT COVER,1,2011-11-14 15:27:00,4.13,14096.0,United Kingdom
466901,576339,20652,BLUE POLKADOT LUGGAGE TAG,2,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466902,576339,20659,ECONOMY LUGGAGE TAG,3,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466903,576339,20675,BLUE POLKADOT BOWL,1,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466904,576339,20677,PINK POLKADOT BOWL,2,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466905,576339,20682,RED RETROSPOT CHILDRENS UMBRELLA,3,2011-11-14 15:27:00,6.63,14096.0,United Kingdom
466906,576339,20707,CRAZY DAISY HEART DECORATION,1,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466907,576339,20713,JUMBO BAG OWLS,2,2011-11-14 15:27:00,4.13,14096.0,United Kingdom
466908,576339,20717,STRAWBERRY SHOPPER BAG,2,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466909,576339,20718,RED RETROSPOT SHOPPER BAG,2,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466910,576339,20719,WOODLAND CHARLOTTE BAG,4,2011-11-14 15:27:00,1.63,14096.0,United Kingdom
466911,576339,20723,STRAWBERRY CHARLOTTE BAG,4,2011-11-14 15:27:00,1.63,14096.0,United Kingdom
466912,576339,20724,RED RETROSPOT CHARLOTTE BAG,2,2011-11-14 15:27:00,1.63,14096.0,United Kingdom
466913,576339,20725,LUNCH BAG RED RETROSPOT,4,2011-11-14 15:27:00,4.13,14096.0,United Kingdom
466914,576339,20726,LUNCH BAG WOODLAND,1,2011-11-14 15:27:00,4.13,14096.0,United Kingdom
466915,576339,20728,LUNCH BAG CARS BLUE,1,2011-11-14 15:27:00,4.13,14096.0,United Kingdom
466916,576339,20749,ASSORTED COLOUR MINI CASES,2,2011-11-14 15:27:00,16.63,14096.0,United Kingdom
466917,576339,20763,DAISY SKETCHBOOK,1,2011-11-14 15:27:00,7.46,14096.0,United Kingdom
466918,576339,20764,ABSTRACT CIRCLES SKETCHBOOK,1,2011-11-14 15:27:00,7.46,14096.0,United Kingdom
466919,576339,20765,CHRYSANTHEMUM SKETCHBOOK,2,2011-11-14 15:27:00,7.46,14096.0,United Kingdom
466920,576339,20829,GLITTER HANGING BUTTERFLY STRING,3,2011-11-14 15:27:00,4.13,14096.0,United Kingdom
466921,576339,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,4,2011-11-14 15:27:00,5.79,14096.0,United Kingdom
466922,576339,20961,STRAWBERRY BATH SPONGE,4,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466923,576339,20963,APPLE BATH SPONGE,3,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466924,576339,20969,RED FLORAL FELTCRAFT SHOULDER BAG,2,2011-11-14 15:27:00,7.46,14096.0,United Kingdom
466925,576339,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,1,2011-11-14 15:27:00,7.46,14096.0,United Kingdom
466926,576339,20971,PINK BLUE FELT CRAFT TRINKET BOX,2,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466927,576339,20972,PINK CREAM FELT CRAFT TRINKET BOX,2,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466928,576339,20973,12 PENCIL SMALL TUBE WOODLAND,10,2011-11-14 15:27:00,1.25,14096.0,United Kingdom
466929,576339,21025,SPACE FROG,2,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466930,576339,21028,NINJA RABBIT BLACK,2,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466931,576339,21030,SPACE CADET RED,2,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466932,576339,21035,SET/2 RED RETROSPOT TEA TOWELS,3,2011-11-14 15:27:00,6.63,14096.0,United Kingdom
466933,576339,21039,RED RETROSPOT SHOPPING BAG,1,2011-11-14 15:27:00,5.79,14096.0,United Kingdom
466934,576339,21055,TOOL BOX SOFT TOY,3,2011-11-14 15:27:00,16.63,14096.0,United Kingdom
466935,576339,21056,DOCTOR'S BAG SOFT TOY,3,2011-11-14 15:27:00,16.63,14096.0,United Kingdom
466936,576339,21070,VINTAGE BILLBOARD MUG,1,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466937,576339,21080,SET/20 RED RETROSPOT PAPER NAPKINS,2,2011-11-14 15:27:00,0.83,14096.0,United Kingdom
466938,576339,21090,SET/6 COLLAGE PAPER PLATES,5,2011-11-14 15:27:00,0.83,14096.0,United Kingdom
466939,576339,21098,CHRISTMAS TOILET ROLL,34,2011-11-14 15:27:00,2.46,14096.0,United Kingdom
466940,576339,21112,SWISS ROLL TOWEL PINK SPOTS,4,2011-11-14 15:27:00,5.79,14096.0,United Kingdom
466941,576339,21114,LAVENDER SCENTED FABRIC HEART,2,2011-11-14 15:27:00,10.79,14096.0,United Kingdom
466942,576339,21126,SET OF 6 GIRLS CELEBRATION CANDLES,1,2011-11-14 15:27:00,1.25,14096.0,United Kingdom
466943,576339,21137,BLACK RECORD COVER FRAME,1,2011-11-14 15:27:00,7.46,14096.0,United Kingdom
466944,576339,21147,JINGLE BELLS TREE DECORATION,4,2011-11-14 15:27:00,2.46,14096.0,United Kingdom

In [52]:
invoice_576339.nunique()

InvoiceNo        1
StockCode      541
Description    541
Quantity        29
InvoiceDate      1
UnitPrice       31
CustomerID       1
Country          1
LineValue      134
dtype: int64

In [53]:
invoice_576339[
    [
        "StockCode",
        "Description",
        "Quantity",
        "UnitPrice",
        "CustomerID"
    ]
].drop_duplicates().shape

(542, 5)

In [54]:
exact_duplicate_group=(
    df.groupby(
        [
              "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
        ]
    ).size().reset_index(name="Count")
)
exact_duplicate_group=exact_duplicate_group[exact_duplicate_group["Count"]>1]
print("Exact duplicate groups:", len(exact_duplicate_group))
print("Rows involved in duplicate groups:",
      exact_duplicate_group["Count"].sum())

Exact duplicate groups: 4837
Rows involved in duplicate groups: 10062

In [55]:
exact_duplicate_group.sort_values(
    "Count",
    ascending=False
).head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Count
146380,555524,22698,PINK REGENCY TEACUP AND SAUCER,1,2011-06-05 11:37:00,2.95,16923.0,United Kingdom,20
146379,555524,22697,GREEN REGENCY TEACUP AND SAUCER,1,2011-06-05 11:37:00,2.95,16923.0,United Kingdom,12
303127,572861,22775,PURPLE DRAWERKNOB ACRYLIC EDWARDIAN,12,2011-10-26 12:46:00,1.25,14102.0,United Kingdom,8
35473,541266,21754,HOME BUILDING BLOCK WORD,1,2011-01-16 16:25:00,5.95,15673.0,United Kingdom,6
16696,538514,21756,BATH BUILDING BLOCK WORD,1,2010-12-12 14:27:00,5.95,15044.0,United Kingdom,6
35474,541266,21755,LOVE BUILDING BLOCK WORD,1,2011-01-16 16:25:00,5.95,15673.0,United Kingdom,6
298989,572344,M,Manual,48,2011-10-24 10:43:00,1.50,14607.0,United Kingdom,6
30356,540524,21756,BATH BUILDING BLOCK WORD,1,2011-01-09 12:53:00,5.95,16735.0,United Kingdom,6
361129,578289,23395,BELLE JARDINIERE CUSHION COVER,1,2011-11-23 14:07:00,3.75,17841.0,United Kingdom,6
16774,538517,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-12 16:05:00,3.75,17618.0,United Kingdom,5
319059,574481,23084,RABBIT NIGHT LIGHT,1,2011-11-04 12:45:00,2.08,18022.0,United Kingdom,5
7453,537224,70007,HI TEC ALPINE HAND WARMER,1,2010-12-05 16:24:00,1.65,13174.0,United Kingdom,5
86942,547712,22699,ROSES REGENCY TEACUP AND SAUCER,1,2011-03-24 19:31:00,2.95,16905.0,United Kingdom,5
107367,550331,85202,HANGING WOOD AND FELT HEART,1,2011-04-17 13:43:00,0.42,15555.0,United Kingdom,5
59463,544463,22256,FELT FARM ANIMAL CHICKEN,1,2011-02-20 14:31:00,1.25,12988.0,United Kingdom,4
132354,553657,22131,FOOD CONTAINER SET 3 LOVE HEART,1,2011-05-18 11:28:00,1.95,14583.0,United Kingdom,4
234350,566258,23071,MARIE ANTOINETTE TRINKET BOX GOLD,1,2011-09-11 12:45:00,12.50,13124.0,United Kingdom,4
59090,544450,47567B,TEA TIME KITCHEN APRON,1,2011-02-20 12:23:00,5.95,17811.0,United Kingdom,4
36390,541414,21755,LOVE BUILDING BLOCK WORD,1,2011-01-17 16:14:00,5.95,18212.0,United Kingdom,4
30374,540524,84755,COLOUR GLASS T-LIGHT HOLDER HANGING,8,2011-01-09 12:53:00,0.65,16735.0,United Kingdom,4

In [56]:
duplicated_row_count=(
    exact_duplicate_group["Count"]-1
).sum()

In [57]:
duplicated_extra__value=0
for _,row in exact_duplicate_group.iterrows():
    duplicated_extra__value+=(
        (row["Count"]-1)*
        row["UnitPrice"]*
        row["Quantity"]
    )
print("Extra duplicate rows:",duplicated_row_count)
print("Extra Duplicate Value:",duplicated_extra__value)

Extra duplicate rows: 5225
Extra Duplicate Value: 21546.3900000003

In [58]:
exact_duplicate_group.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Count
491,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom,2
499,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom,2
510,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom,2
511,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom,2
537,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom,2

In [59]:
duplicate_invoice_summary = (
    exact_duplicate_group
    .groupby("InvoiceNo")
    .agg(
        duplicate_groups=("Count", "size"),
        rows_in_duplicate_groups=("Count", "sum"),
        extra_duplicate_rows=("Count", lambda x: (x - 1).sum())
    )
    .sort_values("extra_duplicate_rows", ascending=False)
)

print(duplicate_invoice_summary.head(20))

           duplicate_groups  rows_in_duplicate_groups  extra_duplicate_rows
InvoiceNo
555524                    6                        40                    34
547651                   26                        57                    31
579458                   25                        53                    28
574481                   22                        49                    27
572103                   23                        50                    27
577482                   26                        52                    26
537781                   22                        47                    25
552285                   24                        48                    24
569897                   19                        40                    21
578041                   15                        36                    21
580305                   18                        39                    21
575117                   19                        40                    21
578921                   18                        38                    20
578781                   19                        39                    20
578998                   15                        34                    19
578289                    8                        26                    18
572861                    7                        25                    18
537224                   13                        30                    17
547498                   13                        29                    16
536796                   15                        31                    16

In [60]:
print("Invoices containing exact duplicate groups:",
      duplicate_invoice_summary.shape[0])

print("Total invoices:",
      df["InvoiceNo"].nunique())
duplicate_invoice_summary.shape[0]

Invoices containing exact duplicate groups: 1903
Total invoices: 25900

1903

In [61]:
duplicate_invoice_summary["extra_duplicate_rows"].describe()

count    1903.000000
mean        2.745665
std         3.122028
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max        34.000000
Name: extra_duplicate_rows, dtype: float64

In [62]:
duplicate_extra_pct = (
    duplicated_row_count / len(df) * 100
)

print(f"Extra duplicate rows: {duplicated_row_count:,}")
print(f"Percentage of dataset: {duplicate_extra_pct:.2f}%")

Extra duplicate rows: 5,225
Percentage of dataset: 0.96%

In [63]:
total_line_value = df["LineValue"].sum()

duplicate_value_pct = (
    duplicated_extra__value / total_line_value * 100
)

print(f"Potential duplicate value: £{duplicated_extra__value:,.2f}")
print(f"Percentage of total line value: {duplicate_value_pct:.2f}%")

Potential duplicate value: £21,546.39
Percentage of total line value: 0.22%

In [64]:
print("Unique StockCodes:", df["StockCode"].nunique())

print("\nTop StockCodes:")
print(df["StockCode"].value_counts().head(30))

Unique StockCodes: 4070

Top StockCodes:
StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
84879     1502
22720     1477
22197     1476
21212     1385
20727     1350
22383     1348
22457     1280
23203     1267
POST      1256
22386     1251
22469     1239
22960     1229
21931     1214
22086     1210
22411     1202
20728     1197
22382     1192
22961     1182
22666     1180
23298     1179
22699     1138
22384     1137
23209     1135
82482     1129
22993     1111
Name: count, dtype: int64

In [65]:
print("Unique descriptions:", df["Description"].nunique())

print("\nTop descriptions:")
print(df["Description"].value_counts().head(30))

Unique descriptions: 4223

Top descriptions:
Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
ASSORTED COLOUR BIRD ORNAMENT         1501
SET OF 3 CAKE TINS PANTRY DESIGN      1473
PACK OF 72 RETROSPOT CAKE CASES       1385
LUNCH BAG  BLACK SKULL.               1350
NATURAL SLATE HEART CHALKBOARD        1280
POSTAGE                               1252
JUMBO BAG PINK POLKADOT               1251
HEART OF WICKER SMALL                 1237
JAM MAKING SET WITH JARS              1229
JUMBO STORAGE BAG SUKI                1214
PAPER CHAIN KIT 50'S CHRISTMAS        1210
JUMBO SHOPPER VINTAGE RED PAISLEY     1202
LUNCH BAG CARS BLUE                   1197
LUNCH BAG SPACEBOY DESIGN             1192
JAM MAKING SET PRINTED                1182
RECIPE BOX PANTRY YELLOW DESIGN       1180
SPOTTY BUNTING                        1172
LUNCH BAG SUKI DESIGN                 1139
ROSES REGENCY TEACUP AND SAUCER       1138
LUNCH BAG PINK POLKADOT               1137
WOODEN PICTURE FRAME WHITE FINISH     1129
SET OF 4 PANTRY JELLY MOULDS          1111
ALARM CLOCK BAKELIKE RED              1107
GREEN REGENCY TEACUP AND SAUCER       1085
LUNCH BAG APPLE DESIGN                1084
Name: count, dtype: int64

In [66]:
special_stockcodes = (
    df.groupby("StockCode")
      .agg(
          rows=("StockCode", "size"),
          descriptions=("Description", "nunique"),
          total_quantity=("Quantity", "sum"),
          total_value=("LineValue", "sum")
      )
      .sort_values("rows", ascending=False)
)

special_stockcodes.head(30)

           rows  descriptions  total_quantity  total_value
StockCode
85123A     2313             4           38830     97894.50
22423      2203             3           12980    164762.19
85099B     2159             1           47363     92356.03
47566      1727             1           18022     98302.98
20725      1639             2           18979     35187.31
84879      1502             2           36221     58959.73
22720      1477             1            7286     37413.44
22197      1476             2           56450     50987.47
21212      1385             1           36039     21059.72
20727      1350             1           12112     22219.01
22383      1348             2           12405     22318.64
22457      1280             1            9120     27995.36
23203      1267             4           20013     40991.38
POST       1256             1            6353     66230.64
22386      1251             1           21009     41619.66
22469      1239             1           17791     31899.85
22960      1229             1            8470     36116.09
21931      1214             1           13320     30167.79
22086      1210             1           18902     63791.94
22411      1202             1           12248     28012.48
20728      1197             1           11603     21423.13
22382      1192             1           10305     17850.01
22961      1182             1           16081     25235.23
22666      1180             1            8146     25819.55
23298      1179             2            8534     42700.02
22699      1138             1            9441     27944.92
22384      1137             1           10363     17198.99
23209      1135             4           13249     21384.37
82482      1129             1            8773     22531.71
22993      1111             1           12604     16422.23

In [67]:
multi_description_codes = (
    df.groupby("StockCode")["Description"]
      .nunique()
      .sort_values(ascending=False)
)

multi_description_codes.head(20)
multi_description_codes[multi_description_codes > 1].shape
for code in multi_description_codes[multi_description_codes > 1].head(10).index:
    print("\nStockCode:", code)
    print(df.loc[df["StockCode"] == code, "Description"].unique())

StockCode: 20713
['JUMBO BAG OWLS' nan 'wrongly marked. 23343 in box' 'wrongly coded-23343'
 'found' 'Found' 'wrongly marked 23343' 'Marked as 23343'
 'wrongly coded 23343']

StockCode: 23084
['RABBIT NIGHT LIGHT' nan 'temp adjustment'
 'allocate stock for dotcom orders ta'
 'add stock to allocate online orders' 'for online retail orders' 'Amazon'
 'website fixed']

StockCode: 21830
['ASSORTED CREEPY CRAWLIES' 'MERCHANT CHANDLER CREDIT ERROR, STO'
 'sold as 1' '?' 'damaged' 'OOPS ! adjustment' nan]

StockCode: 85175
['CACTI T-LIGHT CANDLES' 'Amazon sold sets' 'dotcom sold sets'
 'wrongly sold sets' '? sold as sets?' 'check' nan]

StockCode: 72807A
['SET/3 ROSE CANDLE IN JEWELLED BOX' 'wet pallet' 'damages' '???missing'
 'AMAZON']

StockCode: 85172
['HYACINTH BULB T-LIGHT CANDLES' 'Dotcom set' 'wrongly sold as sets'
 '?sold as sets?' 'check']

StockCode: 23343
['JUMBO BAG VINTAGE CHRISTMAS ' 'came coded as 20713'
 'wrongly coded 20713' '20713 wrongly marked' 20713]

StockCode: 21181
['PLEASE ONE PERSON METAL SIGN' 'on cargo order' 'adjustment' 'check' nan
 'dotcom']

StockCode: 23131
['MISTLETOE HEART WREATH CREAM' 'MISELTOE HEART WREATH WHITE'
 'MISELTOE HEART WREATH CREAM' '?' 'had been put aside' nan]

StockCode: 85185B
['PINK HORSE SOCK PUPPET' '?' nan 'Found in w/hse'
 'PINK HORSE SOCK PUPPET KIT']

In [68]:
df_clean = df.copy()

print("Original rows:", len(df))
print("Cleaning copy rows:", len(df_clean))
df_clean["is_exact_duplicate"] = df_clean.duplicated(keep=False)
df_clean["is_zero_price"] = df_clean["UnitPrice"] == 0
df_clean["is_negative_price"] = df_clean["UnitPrice"] < 0
df_clean["is_postage"] = df_clean["StockCode"].astype(str).str.upper() == "POST"
print("Exact duplicates:", df_clean["is_exact_duplicate"].sum())
print("Negative quantity:", df_clean["is_negative_quantity"].sum())
print("Zero price:", df_clean["is_zero_price"].sum())
print("Negative price:", df_clean["is_negative_price"].sum())
print("Postage:", df_clean["is_postage"].sum())

Original rows: 541909
Cleaning copy rows: 541909
Exact duplicates: 10147

KeyError: 'is_negative_quantity'

In [69]:
# Create the missing boolean column
df_clean["is_negative_quantity"] = df_clean["Quantity"] < 0

# Create the other flag columns
df_clean["is_zero_price"] = df_clean["UnitPrice"] == 0
df_clean["is_negative_price"] = df_clean["UnitPrice"] < 0
df_clean["is_postage"] = df_clean["StockCode"].astype(str).str.upper() == "POST"

# Print sums
print("Exact duplicates:", df_clean["is_exact_duplicate"].sum())
print("Negative quantity:", df_clean["is_negative_quantity"].sum())
print("Zero price:", df_clean["is_zero_price"].sum())
print("Negative price:", df_clean["is_negative_price"].sum())
print("Postage:", df_clean["is_postage"].sum())

Exact duplicates: 10147
Negative quantity: 10624
Zero price: 2515
Negative price: 2
Postage: 1256

In [70]:
df_clean["StockCode"].head(50)

0     85123A
1      71053
2     84406B
3     84029G
4     84029E
5      22752
6      21730
7      22633
8      22632
9      84879
10     22745
11     22748
12     22749
13     22310
14     84969
15     22623
16     22622
17     21754
18     21755
19     21777
20     48187
21     22960
22     22913
23     22912
24     22914
25     21756
26     22728
27     22727
28     22726
29     21724
30     21883
31     10002
32     21791
33     21035
34     22326
35     22629
36     22659
37     22631
38     22661
39     21731
40     22900
41     21913
42     22540
43     22544
44     22492
45      POST
46     22086
47     22632
48     22633
49    85123A
Name: StockCode, dtype: object

In [71]:
df_clean["record_type"] = "Normal"

In [72]:
df_clean.loc[
    df_clean["is_postage"],
    "record_type"
] = "Postage"

In [73]:
df_clean.loc[
    (df_clean["is_negative_quantity"]) &
    (~df_clean["is_negative_price"]) &
    (~df_clean["is_postage"]),
    "record_type"
] = "Return/Cancellation"

In [74]:
df_clean.loc[
    (df_clean["is_zero_price"]) &
    (df_clean["record_type"] == "Normal"),
    "record_type"
] = "Zero-Price Transaction"

In [75]:
print(df_clean["record_type"].value_counts())

record_type
Normal                    528980
Return/Cancellation        10498
Postage                     1256
Zero-Price Transaction      1175
Name: count, dtype: int64

In [76]:
df_clean[df_clean["is_negative_price"]][
    ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "LineValue", "record_type"]
]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,LineValue,record_type
299983,A563186,B,Adjust bad debt,1,-11062.06,-11062.06,Normal
299984,A563187,B,Adjust bad debt,1,-11062.06,-11062.06,Normal

In [77]:
print("Negative-price rows:", len(df_clean[df_clean["is_negative_price"]]))
print(
    df_clean.loc[
        df_clean["is_negative_price"],
        ["Quantity", "UnitPrice", "LineValue", "record_type"]
    ]
)

Negative-price rows: 2
        Quantity  UnitPrice  LineValue record_type
299983         1  -11062.06  -11062.06      Normal
299984         1  -11062.06  -11062.06      Normal

In [78]:
df_clean.loc[
    df_clean["is_negative_price"],
    "record_type"
] = "Accounting Adjustment"
print(df_clean["record_type"].value_counts())

record_type
Normal                    528978
Return/Cancellation        10498
Postage                     1256
Zero-Price Transaction      1175
Accounting Adjustment          2
Name: count, dtype: int64

In [79]:
df_clean["LineValue"].sum()

np.float64(9747747.934)

In [80]:
zero_price = df_clean[df_clean["is_zero_price"]]

print("Total zero-price rows:", len(zero_price))

print("\nRecord types:")
print(zero_price["record_type"].value_counts())
print("\nZero-price descriptions:")
print(zero_price["Description"].value_counts().head(30))

Total zero-price rows: 2515

Record types:
record_type
Return/Cancellation       1336
Zero-Price Transaction    1175
Postage                      4
Name: count, dtype: int64

Zero-price descriptions:
Description
check                              159
?                                   47
damages                             45
damaged                             43
found                               25
sold as set on dotcom               20
adjustment                          16
Damaged                             14
FRENCH BLUE METAL DOOR SIGN 1        9
thrown away                          9
Unsaleable, destroyed.               9
amazon                               8
FRENCH BLUE METAL DOOR SIGN 8        8
Found                                8
FRENCH BLUE METAL DOOR SIGN 4        7
FRENCH BLUE METAL DOOR SIGN No       7
OWL DOORSTOP                         7
FRENCH BLUE METAL DOOR SIGN 3        7
RECIPE BOX PANTRY YELLOW DESIGN      7
??                                   7
Amazon                               7
FRENCH BLUE METAL DOOR SIGN 7        6
FRENCH BLUE METAL DOOR SIGN 5        6
FRENCH BLUE METAL DOOR SIGN 6        6
RED KITCHEN SCALES                   6
FRENCH BLUE METAL DOOR SIGN 9        6
MINT KITCHEN SCALES                  6
dotcom                               6
Manual                               6
BOX OF 24 COCKTAIL PARASOLS          5
Name: count, dtype: int64

In [81]:
sales_df = df_clean[
    df_clean["record_type"] == "Normal"
].copy()

print("Analytical sales rows:", len(sales_df))

print("Analytical sales value:",
      sales_df["LineValue"].sum())

Analytical sales rows: 528978
Analytical sales value: 10588582.664

In [82]:
print(sales_df["record_type"].value_counts())

record_type
Normal    528978
Name: count, dtype: int64

In [83]:
print("Rows:", len(sales_df))
print("Columns:", sales_df.columns.tolist())

print("\nDate range:")
print(sales_df["InvoiceDate"].min())
print(sales_df["InvoiceDate"].max())

print("\nQuantity:")
print("Total:", sales_df["Quantity"].sum())
print("Negative:", (sales_df["Quantity"] < 0).sum())
print("Zero:", (sales_df["Quantity"] == 0).sum())

print("\nUnit Price:")
print("Minimum:", sales_df["UnitPrice"].min())
print("Maximum:", sales_df["UnitPrice"].max())
print("Zero:", (sales_df["UnitPrice"] == 0).sum())
print("Negative:", (sales_df["UnitPrice"] < 0).sum())

print("\nLine Value:")
print("Total:", sales_df["LineValue"].sum())
print("Minimum:", sales_df["LineValue"].min())
print("Maximum:", sales_df["LineValue"].max())

Rows: 528978
Columns: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'LineValue', 'is_exact_duplicate', 'is_zero_price', 'is_negative_price', 'is_postage', 'is_negative_quantity', 'record_type']

Date range:
2010-12-01 08:26:00
2011-12-09 12:50:00

Quantity:
Total: 5585226
Negative: 0
Zero: 0

Unit Price:
Minimum: 0.001
Maximum: 13541.33
Zero: 0
Negative: 0

Line Value:
Total: 10588582.664
Minimum: 0.001
Maximum: 168469.6

In [84]:
total_revenue = sales_df["LineValue"].sum()

total_units = sales_df["Quantity"].sum()

unique_invoices = sales_df["InvoiceNo"].nunique()

unique_customers = sales_df["CustomerID"].nunique()

unique_products = sales_df["StockCode"].nunique()

average_order_value = total_revenue / unique_invoices

average_unit_price = total_revenue / total_units


print(f"Total Revenue: £{total_revenue:,.2f}")
print(f"Total Units Sold: {total_units:,}")
print(f"Unique Invoices: {unique_invoices:,}")
print(f"Unique Customers: {unique_customers:,}")
print(f"Unique Products: {unique_products:,}")
print(f"Average Order Value: £{average_order_value:,.2f}")
print(f"Average Revenue per Unit: £{average_unit_price:,.2f}")

Total Revenue: £10,588,582.66
Total Units Sold: 5,585,226
Unique Invoices: 19,884
Unique Customers: 4,338
Unique Products: 3,921
Average Order Value: £532.52
Average Revenue per Unit: £1.90

In [85]:
country_analysis = (
    sales_df
    .groupby("Country")
    .agg(
        Revenue=("LineValue", "sum"),
        Units=("Quantity", "sum"),
        Orders=("InvoiceNo", "nunique"),
        Customers=("CustomerID", "nunique")
    )
    .sort_values("Revenue", ascending=False)
)

country_analysis["Revenue_Share_%"] = (
    country_analysis["Revenue"]
    / total_revenue
    * 100
)

country_analysis.head(10)

                    Revenue    Units  Orders  Customers  Revenue_Share_%
Country
United Kingdom  9016315.144  4662324   17979       3920        85.151294
Netherlands      283889.340   200258      93          9         2.681089
EIRE             283453.960   147173     288          3         2.676977
Germany          207866.140   118147     449         94         1.963116
France           194261.110   111278     387         87         1.834628
Australia        138171.310    83900      56          9         1.304908
Spain             55725.110    27731      88         30         0.526275
Switzerland       53087.900    30527      50         21         0.501369
Japan             37416.370    26016      19          8         0.353365
Belgium           36927.340    22962      98         25         0.348747

In [86]:
country_analysis.head(10).round(2)

                   Revenue    Units  Orders  Customers  Revenue_Share_%
Country
United Kingdom  9016315.14  4662324   17979       3920            85.15
Netherlands      283889.34   200258      93          9             2.68
EIRE             283453.96   147173     288          3             2.68
Germany          207866.14   118147     449         94             1.96
France           194261.11   111278     387         87             1.83
Australia        138171.31    83900      56          9             1.30
Spain             55725.11    27731      88         30             0.53
Switzerland       53087.90    30527      50         21             0.50
Japan             37416.37    26016      19          8             0.35
Belgium           36927.34    22962      98         25             0.35

In [87]:
product_analysis = (
    sales_df
    .groupby(["StockCode", "Description"])
    .agg(
        Revenue=("LineValue", "sum"),
        Units=("Quantity", "sum"),
        Orders=("InvoiceNo", "nunique"),
        Customers=("CustomerID", "nunique")
    )
    .sort_values("Revenue", ascending=False)
)

product_analysis["Revenue_Share_%"] = (
    product_analysis["Revenue"] / total_revenue * 100
)

print("Top 20 products by transaction value:")
display(product_analysis.head(20).round(2))

Top 20 products by transaction value:

,,Revenue,Units,Orders,Customers,Revenue_Share_%
StockCode,Description,,,,,
DOT,DOTCOM POSTAGE,206248.77,706,706,1,1.95
22423,REGENCY CAKESTAND 3 TIER,174484.74,13879,1988,881,1.65
23843,"PAPER CRAFT , LITTLE BIRDIE",168469.60,80995,1,1,1.59
85123A,WHITE HANGING HEART T-LIGHT HOLDER,104340.29,37599,2189,856,0.99
47566,PARTY BUNTING,99504.33,18295,1685,708,0.94
85099B,JUMBO BAG RED RETROSPOT,94340.05,48474,2089,635,0.89
23166,MEDIUM CERAMIC TOP STORAGE JAR,81700.92,78033,247,138,0.77
M,Manual,78110.27,7224,289,197,0.74
23084,RABBIT NIGHT LIGHT,66964.99,30788,994,450,0.63
22086,PAPER CHAIN KIT 50'S CHRISTMAS,64952.29,19355,1160,613,0.61
84879,ASSORTED COLOUR BIRD ORNAMENT,59094.93,36461,1455,678,0.56
79321,CHILLI LIGHTS,54117.76,10306,661,205,0.51
23298,SPOTTY BUNTING,42548.13,8327,1140,571,0.40
22386,JUMBO BAG PINK POLKADOT,42436.24,21465,1218,372,0.40
21137,BLACK RECORD COVER FRAME,40652.13,11656,375,140,0.38
22502,PICNIC BASKET WICKER 60 PIECES,39619.50,61,2,1,0.37
23284,DOORMAT KEEP CALM AND COME IN,38166.64,5491,728,378,0.36
22720,SET OF 3 CAKE TINS PANTRY DESIGN,38158.39,7493,1385,640,0.36
22960,JAM MAKING SET WITH JARS,37128.88,8706,1132,573,0.35
82484,WOOD BLACK BOARD ANT WHITE FINISH,36030.22,6020,685,285,0.34

In [88]:
sales_df["Month"] = sales_df["InvoiceDate"].dt.to_period("M")

monthly_analysis = (
    sales_df
    .groupby("Month")
    .agg(
        Revenue=("LineValue", "sum"),
        Units=("Quantity", "sum"),
        Orders=("InvoiceNo", "nunique"),
        Customers=("CustomerID", "nunique")
    )
)

monthly_analysis["Revenue_Growth_%"] = (
    monthly_analysis["Revenue"].pct_change() * 100
)

display(monthly_analysis.round(2))

            Revenue   Units  Orders  Customers  Revenue_Growth_%
Month
2010-12   819316.14  359019    1557        885               NaN
2011-01   686226.13  387534    1084        741            -16.24
2011-02   520465.89  283401    1099        758            -24.16
2011-03   712301.79  377286    1450        974             36.86
2011-04   534398.67  308680    1244        854            -24.98
2011-05   757177.27  395495    1678       1056             41.69
2011-06   756203.42  388971    1529        991             -0.13
2011-07   713896.54  401553    1470        948             -5.59
2011-08   753779.78  421527    1346        934              5.59
2011-09  1052692.95  570539    1826       1263             39.66
2011-10  1146953.34  623052    2023       1363              8.95
2011-11  1499143.35  754045    2761       1663             30.71
2011-12   636027.39  314124     817        615            -57.57

In [89]:
customer_analysis = (
    sales_df
    .groupby("CustomerID")
    .agg(
        Revenue=("LineValue", "sum"),
        Units=("Quantity", "sum"),
        Orders=("InvoiceNo", "nunique"),
        Products=("StockCode", "nunique")
    )
    .sort_values("Revenue", ascending=False)
)

customer_analysis["Revenue_Share_%"] = (
    customer_analysis["Revenue"] / total_revenue * 100
)

display(customer_analysis.head(20).round(2))

              Revenue   Units  Orders  Products  Revenue_Share_%
CustomerID
14646.0     279138.02  196844      72       699             2.64
18102.0     259657.30   64124      60       150             2.45
17450.0     194550.79   69993      46       124             1.84
16446.0     168472.50   80997       2         3             1.59
14911.0     143825.06   80265     201      1787             1.36
12415.0     124564.53   77373      20       443             1.18
14156.0     117379.63   57885      55       714             1.11
17511.0      91062.38   64549      31       453             0.86
12346.0      77183.60   74215       1         1             0.73
16029.0      72882.09   40207      62        43             0.69
16684.0      66653.56   50255      28       119             0.63
14096.0      65164.79   16352      17      1119             0.62
13694.0      65039.62   63312      50       366             0.61
15311.0      60767.90   38194      91       567             0.57
13089.0      58825.83   31070      97       636             0.56
17949.0      58510.48   30546      45        29             0.55
15769.0      56252.72   29672      26        26             0.53
15061.0      54534.14   28920      48        70             0.52
14298.0      51527.30   58343      44       884             0.49
14088.0      50491.81   12665      13       379             0.48

In [90]:
top_10_customer_share = (
    customer_analysis.head(10)["Revenue"].sum()
    / total_revenue * 100
)

top_50_customer_share = (
    customer_analysis.head(50)["Revenue"].sum()
    / total_revenue * 100
)

print(f"Top 10 customers' revenue share: {top_10_customer_share:.2f}%")
print(f"Top 50 customers' revenue share: {top_50_customer_share:.2f}%")

Top 10 customers' revenue share: 14.44%
Top 50 customers' revenue share: 27.85%

In [91]:
price_analysis = (
    sales_df
    .groupby("StockCode")
    .agg(
        Revenue=("LineValue", "sum"),
        Units=("Quantity", "sum"),
        Avg_UnitPrice=("UnitPrice", "mean"),
        Orders=("InvoiceNo", "nunique")
    )
    .sort_values("Revenue", ascending=False)
)

display(price_analysis.head(20).round(2))

             Revenue  Units  Avg_UnitPrice  Orders
StockCode
DOT        206248.77    706         292.14     706
22423      174484.74  13879          13.98    1988
23843      168469.60  80995           2.08       1
85123A     104518.80  37660           3.12    2198
47566       99504.33  18295           5.79    1685
85099B      94340.05  48474           2.49    2089
23166       81700.92  78033           1.47     247
M           78110.27   7224         230.86     289
23084       66964.99  30788           2.38     994
22086       64952.29  19355           3.36    1160
84879       59094.93  36461           1.72    1455
79321       54117.76  10306           6.79     661
22502       51426.62   1940          10.27     463
22197       51354.02  56921           1.04    1392
23298       43182.83   8473           5.52    1146
22386       42436.24  21465           2.60    1218
23203       42067.78  20503           2.27    1231
21137       40652.13  11656           4.21     375
23284       38166.64   5491           8.77     728
22720       38158.39   7493           5.83    1385

In [92]:
top_transactions = (
    sales_df
    .sort_values("LineValue", ascending=False)
    [
        [
            "InvoiceNo",
            "StockCode",
            "Description",
            "Quantity",
            "UnitPrice",
            "LineValue",
            "CustomerID",
            "Country",
            "InvoiceDate"
        ]
    ]
)

display(top_transactions.head(20))

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,LineValue,CustomerID,Country,InvoiceDate
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,168469.60,16446.0,United Kingdom,2011-12-09 09:15:00
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,77183.60,12346.0,United Kingdom,2011-01-18 10:01:00
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,38970.00,15098.0,United Kingdom,2011-06-10 15:28:00
15017,537632,AMAZONFEE,AMAZON FEE,1,13541.33,13541.33,NaN,United Kingdom,2010-12-07 15:08:00
299982,A563185,B,Adjust bad debt,1,11062.06,11062.06,NaN,United Kingdom,2011-08-12 14:50:00
348325,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,5.06,7144.72,17450.0,United Kingdom,2011-09-20 11:05:00
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,6539.40,15749.0,United Kingdom,2011-01-11 12:55:00
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,6539.40,15749.0,United Kingdom,2011-04-18 13:20:00
421601,573003,23084,RABBIT NIGHT LIGHT,2400,2.08,4992.00,14646.0,Netherlands,2011-10-27 12:11:00
52709,540815,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2.55,4921.50,15749.0,United Kingdom,2011-01-11 12:55:00
467804,576365,22086,PAPER CHAIN KIT 50'S CHRISTMAS,688,6.95,4781.60,NaN,United Kingdom,2011-11-14 17:55:00
160542,550461,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2.40,4632.00,15749.0,United Kingdom,2011-04-18 13:20:00
52772,540818,48185,DOORMAT FAIRY CAKE,670,6.75,4522.50,15749.0,United Kingdom,2011-01-11 12:57:00
297723,562955,DOT,DOTCOM POSTAGE,1,4505.17,4505.17,NaN,United Kingdom,2011-08-11 10:14:00
244419,558526,23173,REGENCY TEAPOT ROSES,540,8.15,4401.00,17949.0,United Kingdom,2011-06-30 11:01:00
268028,560373,M,Manual,1,4287.63,4287.63,NaN,United Kingdom,2011-07-18 12:30:00
160544,550461,48185,DOORMAT FAIRY CAKE,670,6.35,4254.50,15749.0,United Kingdom,2011-04-18 13:20:00
291249,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,1.45,4176.00,12931.0,United Kingdom,2011-08-04 18:06:00
422351,573077,M,Manual,1,4161.06,4161.06,12536.0,France,2011-10-27 14:13:00
422376,573080,M,Manual,1,4161.06,4161.06,12536.0,France,2011-10-27 14:20:00

# Sql Queries

In [93]:
pip install duckdb

Collecting duckdb
  Downloading duckdb-1.5.6-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.6-cp314-cp314-win_amd64.whl (13.7 MB)
   ---------------------------------------- 0.0/13.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.7 MB ? eta -:--:--
    --------------------------------------- 0.3/13.7 MB ? eta -:--:--
   --- ------------------------------------ 1.0/13.7 MB 3.2 MB/s eta 0:00:04
   --- ------------------------------------ 1.3/13.7 MB 2.2 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/13.7 MB 2.8 MB/s eta 0:00:05
   ------- -------------------------------- 2.6/13.7 MB 2.6 MB/s eta 0:00:05
   --------- ------------------------------ 3.1/13.7 MB 2.6 MB/s eta 0:00:05
   ---------- ----------------------------- 3.7/13.7 MB 2.7 MB/s eta 0:00:04
   ------------ --------------------------- 4.5/13.7 MB 2.7 MB/s eta 0:00:04
   --------------- ------------------------ 5.2/13.7 MB 2.8 MB/s eta 0:00:04
   --------------- ------------------------ 5.2/13.7 MB 2.8 MB/s eta 0:00:04
   --------------- ------------------------ 5.2/13.7 MB 2.8 MB/s eta 0:00:04
   --------------- ------------------------ 5.2/13.7 MB 2.8 MB/s eta 0:00:04
   ---------------- ----------------------- 5.8/13.7 MB 2.1 MB/s eta 0:00:04
   ----------------- ---------------------- 6.0/13.7 MB 2.1 MB/s eta 0:00:04
   ------------------- -------------------- 6.6/13.7 MB 2.1 MB/s eta 0:00:04
   ---------------------- ----------------- 7.6/13.7 MB 2.3 MB/s eta 0:00:03
   ----------------------- ---------------- 8.1/13.7 MB 2.3 MB/s eta 0:00:03
   ------------------------ --------------- 8.4/13.7 MB 2.3 MB/s eta 0:00:03
   ------------------------ --------------- 8.4/13.7 MB 2.3 MB/s eta 0:00:03
   ------------------------ --------------- 8.4/13.7 MB 2.3 MB/s eta 0:00:03
   ------------------------ --------------- 8.4/13.7 MB 2.3 MB/s eta 0:00:03
   -------------------------- ------------- 9.2/13.7 MB 2.0 MB/s eta 0:00:03
   ----------------------------- ---------- 10.0/13.7 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 10.5/13.7 MB 2.1 MB/s eta 0:00:02
   --------------------------------- ------ 11.5/13.7 MB 2.2 MB/s eta 0:00:01
   ---------------------------------- ----- 11.8/13.7 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 12.6/13.7 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 12.6/13.7 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 12.6/13.7 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 12.6/13.7 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  13.6/13.7 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 13.7/13.7 MB 2.0 MB/s  0:00:06
Installing collected packages: duckdb
Successfully installed duckdb-1.5.6
Note: you may need to restart the kernel to use updated packages.

In [103]:
import duckdb as du
con=du.connect()
con.register("sales",sales_df)

In [104]:
for col in sales_df.columns:
    if isinstance(sales_df[col].dtype, pd.PeriodDtype):
        sales_df[col] = sales_df[col].astype(str)

In [111]:
print(
    con.execute("SELECT COUNT(*) AS rows FROM Sales").fetchdf()
)

     rows
0  528978

## Core KPI

In [107]:
query='''
SELECT
    SUM(LineValue) AS total_transaction_value,
    SUM(Quantity) AS total_units,
    COUNT(DISTINCT InvoiceNo) AS invoices,
    COUNT(DISTINCT CustomerID) AS customers,
    COUNT(DISTINCT StockCode) AS products
FROM sales;
'''

In [110]:
result=con.execute(query).fetch_df()
result

   total_transaction_value  total_units  invoices  customers  products
0             1.058858e+07    5585226.0     19884       4338      3921

## COUNTRY ANALYSIS

In [113]:
Q2='''
SELECT
    Country,
    SUM(LineValue) AS transaction_value,
    SUM(Quantity) AS units,
    COUNT(DISTINCT InvoiceNo) AS invoices,
    COUNT(DISTINCT CustomerID) AS customers
FROM sales
GROUP BY Country
ORDER BY transaction_value DESC;
'''

In [114]:
r2=con.execute(Q2).fetch_df()
r2

                 Country  transaction_value      units  invoices  customers
0         United Kingdom       9.016315e+06  4662324.0     17979       3920
1            Netherlands       2.838893e+05   200258.0        93          9
2                   EIRE       2.834540e+05   147173.0       288          3
3                Germany       2.078661e+05   118147.0       449         94
4                 France       1.942611e+05   111278.0       387         87
5              Australia       1.381713e+05    83900.0        56          9
6                  Spain       5.572511e+04    27731.0        88         30
7            Switzerland       5.308790e+04    30527.0        50         21
8                  Japan       3.741637e+04    26016.0        19          8
9                Belgium       3.692734e+04    22962.0        98         25
10                Sweden       3.686933e+04    36043.0        34          8
11                Norway       3.329494e+04    19279.0        33         10
12              Portugal       3.123910e+04    16161.0        56         19
13             Singapore       2.127929e+04     5241.0         7          1
14       Channel Islands       2.045044e+04     9491.0        26          9
15               Finland       1.889608e+04    10610.0        41         12
16               Denmark       1.821134e+04     8193.0        18          9
17                 Italy       1.582024e+04     8067.0        35         14
18             Hong Kong       1.551680e+04     4771.0        10          0
19                Cyprus       1.357538e+04     6360.0        15          8
20               Austria       8.742680e+03     4844.0        17         11
21                Israel       8.135260e+03     4409.0         8          3
22                Poland       6.974650e+03     3675.0        19          6
23           Unspecified       4.749790e+03     3300.0        13          4
24                Greece       4.425520e+03     1550.0         5          4
25               Iceland       4.310000e+03     2458.0         7          1
26                   USA       3.580390e+03     2458.0         5          4
27                Canada       3.115440e+03     2762.0         5          4
28                 Malta       2.070590e+03      958.0         5          2
29  United Arab Emirates       1.864780e+03      981.0         2          2
30               Lebanon       1.693880e+03      386.0         1          1
31             Lithuania       1.661060e+03      652.0         4          1
32    European Community       1.159250e+03      490.0         3          1
33                Brazil       1.143600e+03      356.0         1          1
34                   RSA       1.002310e+03      351.0         1          1
35        Czech Republic       7.867400e+02      670.0         2          1
36               Bahrain       7.541400e+02      314.0         3          2
37          Saudi Arabia       1.459200e+02       80.0         1          1

In [135]:
Q3='''
SELECT
    DATE_TRUNC('month', InvoiceDate) AS month,
    SUM(LineValue) AS transaction_value,
    SUM(Quantity) AS units,
    COUNT(DISTINCT InvoiceNo) AS invoices,
    COUNT(DISTINCT CustomerID) AS customers
FROM sales
GROUP BY DATE_TRUNC('month', InvoiceDate)
ORDER BY month;
'''

In [136]:
r3=con.execute(Q3).fetch_df()
r3

        month  transaction_value     units  invoices  customers
0  2010-12-01         819316.140  359019.0      1557        885
1  2011-01-01         686226.130  387534.0      1084        741
2  2011-02-01         520465.890  283401.0      1099        758
3  2011-03-01         712301.790  377286.0      1450        974
4  2011-04-01         534398.671  308680.0      1244        854
5  2011-05-01         757177.270  395495.0      1678       1056
6  2011-06-01         756203.420  388971.0      1529        991
7  2011-07-01         713896.541  401553.0      1470        948
8  2011-08-01         753779.780  421527.0      1346        934
9  2011-09-01        1052692.952  570539.0      1826       1263
10 2011-10-01        1146953.340  623052.0      2023       1363
11 2011-11-01        1499143.350  754045.0      2761       1663
12 2011-12-01         636027.390  314124.0       817        615

## Top Customers

In [137]:
Q4='''
SELECT
    CustomerID,
    SUM(LineValue) AS transaction_value,
    SUM(Quantity) AS units,
    COUNT(DISTINCT InvoiceNo) AS invoices,
    COUNT(DISTINCT StockCode) AS products
FROM sales
WHERE CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY transaction_value DESC
LIMIT 20;
'''

In [138]:
r4=con.execute(Q4).fetch_df()
r4

    CustomerID  transaction_value     units  invoices  products
0      14646.0          279138.02  196844.0        72       699
1      18102.0          259657.30   64124.0        60       150
2      17450.0          194550.79   69993.0        46       124
3      16446.0          168472.50   80997.0         2         3
4      14911.0          143825.06   80265.0       201      1787
5      12415.0          124564.53   77373.0        20       443
6      14156.0          117379.63   57885.0        55       714
7      17511.0           91062.38   64549.0        31       453
8      12346.0           77183.60   74215.0         1         1
9      16029.0           72882.09   40207.0        62        43
10     16684.0           66653.56   50255.0        28       119
11     14096.0           65164.79   16352.0        17      1119
12     13694.0           65039.62   63312.0        50       366
13     15311.0           60767.90   38194.0        91       567
14     13089.0           58825.83   31070.0        97       636
15     17949.0           58510.48   30546.0        45        29
16     15769.0           56252.72   29672.0        26        26
17     15061.0           54534.14   28920.0        48        70
18     14298.0           51527.30   58343.0        44       884
19     14088.0           50491.81   12665.0        13       379

## Data quality Impact

In [140]:
Q5='''
SELECT
    InvoiceNo,
    StockCode,
    Description,
    Quantity,
    UnitPrice,
    LineValue,
    CustomerID,
    Country,
    InvoiceDate
FROM sales
ORDER BY LineValue DESC
LIMIT 20;
'''

In [141]:
r5=con.execute(Q5).fetch_df()
r5

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,LineValue,CustomerID,Country,InvoiceDate
0,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,168469.60,16446.0,United Kingdom,2011-12-09 09:15:00
1,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,77183.60,12346.0,United Kingdom,2011-01-18 10:01:00
2,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,38970.00,15098.0,United Kingdom,2011-06-10 15:28:00
3,537632,AMAZONFEE,AMAZON FEE,1,13541.33,13541.33,NaN,United Kingdom,2010-12-07 15:08:00
4,A563185,B,Adjust bad debt,1,11062.06,11062.06,NaN,United Kingdom,2011-08-12 14:50:00
5,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,5.06,7144.72,17450.0,United Kingdom,2011-09-20 11:05:00
6,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,6539.40,15749.0,United Kingdom,2011-04-18 13:20:00
7,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,6539.40,15749.0,United Kingdom,2011-01-11 12:55:00
8,573003,23084,RABBIT NIGHT LIGHT,2400,2.08,4992.00,14646.0,Netherlands,2011-10-27 12:11:00
9,540815,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2.55,4921.50,15749.0,United Kingdom,2011-01-11 12:55:00
10,576365,22086,PAPER CHAIN KIT 50'S CHRISTMAS,688,6.95,4781.60,NaN,United Kingdom,2011-11-14 17:55:00
11,550461,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2.40,4632.00,15749.0,United Kingdom,2011-04-18 13:20:00
12,540818,48185,DOORMAT FAIRY CAKE,670,6.75,4522.50,15749.0,United Kingdom,2011-01-11 12:57:00
13,562955,DOT,DOTCOM POSTAGE,1,4505.17,4505.17,NaN,United Kingdom,2011-08-11 10:14:00
14,558526,23173,REGENCY TEAPOT ROSES,540,8.15,4401.00,17949.0,United Kingdom,2011-06-30 11:01:00
15,560373,M,Manual,1,4287.63,4287.63,NaN,United Kingdom,2011-07-18 12:30:00
16,550461,48185,DOORMAT FAIRY CAKE,670,6.35,4254.50,15749.0,United Kingdom,2011-04-18 13:20:00
17,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,1.45,4176.00,12931.0,United Kingdom,2011-08-04 18:06:00
18,573077,M,Manual,1,4161.06,4161.06,12536.0,France,2011-10-27 14:13:00
19,573080,M,Manual,1,4161.06,4161.06,12536.0,France,2011-10-27 14:20:00

In [144]:
sales_df.to_excel("Sales.xlsx",engine="openpyxl")